### PR TITLE
Puma

### PR DESCRIPTION
**Pull request by briankung**
Switches to Puma, since it's now the recommended webserver for Heroku: https://devcenter.heroku.com/changelog-items/594

If this new puma server gets deployed, please remember to set this config:

- [ ] `$ heroku config:set MAX_THREADS=1`

Via: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#adding-puma-to-your-application

I made a staging server and it seems to work: https://sleepy-lowlands-8946.herokuapp.com/questions/test

### CODE REVIEW

**Comment by wsf246** [comment]
awesome, thanks!

**Comment by briankung** [comment]
Merge?

**Comment by wsf246** [comment]
Yes!  Will try to do this tonight.

**Comment by briankung** [comment]
Via command line? You could hit the merge button right under the conversation: 
screen shot 2015-02-17 at 3 25 54 pm

**Comment by briankung** [comment]
Thanks for the merge!

**Pull request merged**
